language: cpp

matrix:
  include:
  - env:
    - OCPN_TARGET=stretch-armhf
    - OCPN_BRANCH=master
    - OCPN_STABLE_REPO=rick-gleason/opencpn-plugins-prod
    - OCPN_UNSTABLE_REPO=rick-gleason/opencpn-plugins-beta
    - OCPN_PKG_REPO=rick-gleason/opencpn-plugins-pkg

    - DOCKER_IMAGE=raspbian/stretch

    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"
#    - travis_wait 40 sleep infinity & bash ./ci/travis-build-raspbian-armhf.sh
  - env:
    - OCPN_TARGET=buster-armhf
    - OCPN_BRANCH=master

    - DOCKER_IMAGE=opencpn/raspbian-buster:plugin_build_tooling

    services:
    - docker
    script:
#    - chmod a+x ./ci/travis-build-raspbian-armhf.sh
    - "./ci/travis-build-raspbian-armhf.sh"
#  - env:
#    - OCPN_TARGET=bionic-arm64
#    - OCPN_BRANCH=master
# 
#    - DOCKER_IMAGE=arm64v8/ubuntu:18.04
#
#    services:
#    - docker
#    script:
#    - chmod a+x ./ci/travis-build-raspbian-armhf.sh	
#    - "./ci/travis-build-ubuntu-arm64.sh"

branches:
  only:

